#!/usr/bin/env bash
# Installs and configures HAproxy in a load balancer server
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 24304-web-01 3.236.88.110:80 check\n\tserver 24304-web-02 3.236.5.40:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
